### PR TITLE
Add tor-sticker.svg

### PR DESCRIPTION
**Pull request by alxndr42**
Found at this location:

https://commons.wikimedia.org/wiki/File:Tor-logo-2011-sticker.svg

which references this location:

https://media.torproject.org/image/2011-tor-logo-sticker.svg

### CODE REVIEW

**Comment by elioqoshi** [comment]
Although still used nowadays (not sure if stock or still produced though) these stickers are using the outdated logo and should be updated so I'd suggest not to add that one here.

**Comment by alxndr42** [comment]
Yeah, that's why I added it to the `outdated` folder. If this repo is not actually meant to be "an archive of all Tor images, videos, and related files", removing the `outdated` folder might be better, to prevent confusion.

On a related note: are there any up-to-date sticker designs? Someone is about to get stickers printed for 36C3.

**Comment by elioqoshi** [comment]
Ah sorry I missed that. Good call. I'd be happy to help, @holantonela what do you think?

**Comment by holantonela-zz** [comment]
We're not maintaining this repo. My aim is to have media.torproject.org as the source of trust for these assets. 

re 36c3 stickers, go for them @elioqoshi !!

**Comment by elioqoshi** [comment]
Might be worth archiving this repo then :)

**Comment by ButtonStart** [comment]
```
```

**Review by Klusterfuk90 — APPROVED** [review]

**Pull request closed without merging**
